version: "3.8"

services:
  mongodb:
    image: mongo
    restart: always
    hostname: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123

  flask-backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    hostname: backend
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py
    depends_on:
      - mongodb

  web-client:
    build:
      context: ./web-client
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    hostname: web
    environment:
      VITE_API_URL: "http://flask-backend:5000"
    depends_on:
      - flask-backend